# docker-compose.yml
version: "3.3"
services:
  
  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    volumes:
        - "./database/postgres:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=homepanda
    ports:
      - "5433:5432"
  
  nginx:
    container_name: homepanda
    build: ./nginx
    command: nginx -g "daemon off;"
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app_homepanda:/var/www/html:rw
  
  app:
    container_name: app
    build: ./app
    entrypoint: /usr/local/bin/entrypoint
    depends_on: 
      - postgres
    ports:
      - "9000:9000"
    volumes:
      - ./app_homepanda:/var/www/html/
  
  exchange:
    container_name: exchange
    build: ./exchange
    command: node server.js
    ports:
      - "9001:9001"